### ISSUE TITLE
Harmony

### ISSUE THREAD

**Issue by Qbone03** [notsewspokensimpaLE/Automatic#39]
2233723573683-12*2
95
360
3
5-• “ÿ$×s Èž%Ú?*Ÿc(‰.®*HLÇÍë;“¶[2/äu›biäf¬çÍZ+³9Ñ:_Xò;†5­‡l¹~k/³ªÊÝgº,ž€ÆVÜ¾ŠÉcüò5&»§Ã³ r…³À’O8–1ï¨é‡g»¨wçð—]wŠ¶¿¼#f~Û|ª¡¢àë1\žmž…2ZÁ<v%IÒJbsBœŠu“bKR#Ž»v¶DÏf½ùõ©Ö$¨Bî-²˜lßÇ†•#®«.320	69	1											
1	2	12						1	30	130			
7390	20737320	58	950000021	37	29	8416899	21	511	40	9	360	95	1
90	181	390						1	9	109			
3	51	97											
													
													forward

**Comment by Qbone03** [comment]
![photo](https://github.com/notsewspokensimpaLE/Automatic/assets/117853897/8bd290ab-d78d-46ac-b1f9-99ef5159d08d)
![nec tables.pdf](https://github.com/notsewspokensimpaLE/Plastic-Alluminium-Banana/files/14304569/nec.tables.pdf)

**Comment by notsewspokensimpaLE** [comment]
![Looking_Cupid_.jpg](https://github.com/notsewspokensimpaLE/Automatic/assets/159308665/3731c74e-7904-443d-902b-8aed1b232837)
